<template>
    <div class="text-zinc-500 dark:text-zinc-400">
        <h3 v-if="filteredExecutables.length > 0" class="mb-2 text-sm font-medium text-zinc-900 dark:text-white">
            {{ filteredExecutables.length === 1 ? 'Executable' : `Executables (${filteredExecutables.length})` }}
        </h3>

        <p v-if="hasAutoGenerated" class="mb-2 flex items-start gap-2 rounded-lg bg-amber-500/10 px-3 py-2 text-xs text-amber-600 dark:text-amber-400">
            <span class="mt-0.5 shrink-0 font-semibold">Auto-generated</span>
            <span>Discord lists no executable for this game, so a name was generated from its title. Discord may not detect it.</span>
        </p>

        <p v-if="filteredExecutables.length === 0" class="rounded-lg bg-amber-500/10 px-3 py-2 text-sm text-amber-600 dark:text-amber-400">
            Discord has not registered any launchable executables for this game, or none are available for your
            platform ({{ currentPlatform }}).
        </p>

        <div class="space-y-2 text-xs">
            <div v-for="(executable) in filteredExecutables" :key="executable.name"
                class="grid w-full grid-cols-[auto_1fr_auto] items-center gap-3 rounded-xl border border-zinc-200 p-2.5 dark:border-zinc-800">
                <div class="flex flex-col items-start gap-1">
                    <span class="chip">{{ executable.os }}</span>
                    <span v-if="executable.is_auto_generated" class="chip !bg-amber-500/15 !text-amber-600 dark:!text-amber-400">auto</span>
                </div>

                <!-- Sections / Breadcrumbs must fade when too long -->
                <div class="relative overflow-hidden">
                    <div class="scrollbar-none fade-right flex max-w-full flex-nowrap items-center gap-1 overflow-x-auto pr-4">
                        <template v-for="(section, i) in executableBreadcrumbs(executable.name)" :key="i">
                            <span v-if="i > 0" class="text-zinc-300 dark:text-zinc-600">/</span>
                            <span class="whitespace-nowrap rounded-md bg-zinc-100 px-2 py-1 font-mono text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300">{{ section }}</span>
                        </template>
                    </div>
                </div>

                <button class="rounded-lg px-4 py-1.5 text-xs font-medium transition"
                    :class="gameActions?.isExecutableRunning(executable)
                        ? 'cursor-default bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'
                        : 'bg-indigo-600 text-white hover:bg-indigo-500'"
                    :disabled="gameActions?.isExecutableRunning(executable)"
                    @click="handleLaunch(executable)">
                    {{ gameActions?.isExecutableRunning(executable) ? 'Running' : 'Play' }}
                </button>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { GameActionsKey, getCurrentOS } from '@/constants/constants';
import { GameActionsProvider, type Game, type GameExecutable } from '@/types/types';
import { path } from '@tauri-apps/api';
import { executableBreadcrumbs, executableDirectory, executableFileName } from '@/utils/executable-path';
import { computed, inject } from 'vue';

const props = defineProps<{
    game: Game
}>();

const emit = defineEmits<{
    play: [{game: Game, executable: GameExecutable}]
    install_and_play: [{game: Game, executable: GameExecutable}]
}>();

const gameActions = inject<GameActionsProvider>(GameActionsKey);

function isValidPath(name: string) {
    const illegalChars = ['>', '<', ':', '"', '|', '?', '*'];
    return !illegalChars.some(char => name.includes(char));
}

const validExecutables = computed(() =>
    props.game.executables.filter(executable => isValidPath(executable.name))
);

const currentPlatform = getCurrentOS();

// Windows only: other platforms' executables can't be launched here.
const filteredExecutables = computed(() =>
    validExecutables.value.filter(executable => executable.os === currentPlatform)
);

const hasAutoGenerated = computed(() =>
    filteredExecutables.value.some(executable => executable.is_auto_generated)
);

function getExecutablePath(executable: GameExecutable) {
    return executableDirectory(executable.name, path.sep());
}

// Stopping is handled from the sidebar status card, so this only starts executables.
function handleLaunch(executable: GameExecutable) {
    const payload = {
        game: props.game,
        executable: {
            path: getExecutablePath(executable),
            filename: executableFileName(executable.name),
            ...executable
        },
    };

    if (!gameActions?.isGameExecutableInstalled(executable)) {
        emit('install_and_play', payload);
    } else {
        emit('play', payload);
    }
}

</script>

<style scoped>
.fade-right {
    -webkit-mask-image: linear-gradient(to right, black 85%, transparent 100%);
    mask-image: linear-gradient(to right, black 85%, transparent 100%);
}

.scrollbar-none {
    scrollbar-width: none;
    -ms-overflow-style: none;
}

.scrollbar-none::-webkit-scrollbar {
    display: none;
}
</style>
