[package]
name = "quest-runner"
version = "0.2.0"
description = "Tiny dummy game window used by Discord Quest Completer"
license = "MIT"
publish = false
edition = "2021"

[build-dependencies]
cc = "1.0"

[[bin]]
name = "quest-runner"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true